### ISSUE TITLE
Cache.SetHashed, Cache.ScanHashed function async implementation

### ISSUE THREAD

**Issue by burhancetinkaya** [thepirat000/CachingFramework.Redis#25]
Hi,

Is there any plan to implement async versions of Cache.SetHashed, Cache.ScanHashed methods?

**Comment by thepirat000** [comment]
The only overload of the SetHashed that makes sense to provide an Async version is:

```public void SetHashed<T>(string key, IDictionary<string, T> fieldValues)```

The rest of the overloads are  _almost_ asynchronous since they use Batches and the operations are only enqueued but not awaited.

Also for `ScanHashed`, there is no Async equivalent for the SE.Redis HashScan method that is used internally and this is because this returns an iterator, it will not fetch the data until the iterator is used.

**Comment by moconnell** [comment]
Can we reopen this one? I have a use case. 

In the following code, I am using SetHashed/FetchHashedAsync to store a secondary index. But the mixture between async and sync methods is (I think) causing timeout errors:

```
        private async Task UpdateIndexImpl(string key, Guid correlationId)
        {
            var fieldKey = correlationId.ToString();
            var keys = await _cache.FetchHashedAsync(AuditKeysByCorrelationId, fieldKey, () => Task.FromResult(new HashSet<string> {key}), _lifespan);
            if (!keys.Contains(key))
            {
                keys.Add(key);
                await Task.Run(() => _cache.SetHashed(AuditKeysByCorrelationId, fieldKey, keys, _lifespan)); // <-- occasional timeouts under load
            }

            this.Debug($"{AuditKeysByCorrelationId}:{correlationId} = {keys.ToCsv()}");
        }
```

**Comment by thepirat000** [comment]
what's the purpose of creating a new task and awaiting it? I think you should directly call the _cache.SetHashed since you already awaited the previous call and the `SetHashed` will not block

Just do this: `_cache.SetHashed(AuditKeysByCorrelationId, fieldKey, keys, _lifespan)`

**Comment by moconnell** [comment]
Purpose is to not block the calling thread - aware it’s awaited anyway. I will try your suggestion, but I am fairly sure I tried this already and I will still see the timeout.

Incidentally, having read the implementation, am I correct in saying that it is async under the hood anyway, but you just don’t await it?

**Comment by thepirat000** [comment]
Can you share the exception trace ?


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thepirat000** [comment]
Just added the `SetHashedAsync` method and other mssing async methods to the cache provider (version 7.4.0)

Note `ScanHashed` method cannot be made async.

Feel free to re-open the issue if you're still having problems.

Regards

**Comment by moconnell** [comment]
Hi Federico,

Sorry for the slow response - I was offline over the weekend. Thanks very much for the rapid patch - hopefully this eliminates the issue.

Best,
Matt

**Comment by moconnell** [comment]
Still was able to provoke a timeout - every incidence had the following stack trace - it seems again from reading e.g. [this StackOverflow thread](https://stackoverflow.com/questions/46391414/how-to-solve-a-redis-timeout-on-client-side-with-stackexchange-redis) that it is just the sync methods that time-out.

So I guess the only answer is to use async/await all the way down, if that's possible. 

```
StackExchange.Redis.RedisTimeoutException occurred
  HResult=-2146233083
  HelpLink=http://stackexchange.github.io/StackExchange.Redis/Timeouts
  Message=Timeout performing EXISTS audit:keysByCorrelationId, inst: 2334, mgr: ProcessReadQueue, err: never, queue: 2402, qu: 1, qs: 2401, qc: 0, wr: 0, wq: 0, in: 8192, ar: 1, clientName: WSP18652WN, serverEndpoint: Unspecified/localhost:6379, keyHashSlot: 3862, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=31,Free=32736,Min=8,Max=32767) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
  Source=StackExchange.Redis
  StackTrace:
       at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
       at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
       at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags)
       at CachingFramework.Redis.Providers.RedisCacheProvider.SetMaxExpiration(IBatch batch, String key, Nullable`1 ttl)
       at CachingFramework.Redis.Providers.RedisCacheProvider.SetHashed[T](String key, String field, T value, Nullable`1 ttl, When when)
       at CachingFramework.Redis.Providers.RedisCacheProvider.SetHashed[T](String key, String field, T value, String[] tags, Nullable`1 ttl, When when)
       at CachingFramework.Redis.Providers.RedisCacheProvider.<FetchHashedAsync>d__6`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at CachingFramework.Redis.Providers.RedisCacheProvider.<FetchHashedAsync>d__5`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at CachingFramework.Redis.Providers.RedisCacheProvider.<FetchHashedAsync>d__4`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at SPMO.Cache.Redis.RedisCache.<FetchHashedAsync>d__3`1.MoveNext() in E:\dev\SPMO\trunk\SPMO.Cache.Redis\RedisCache.cs:line 26
```

**Comment by moconnell** [comment]
We are just using the [Windows port](https://github.com/MicrosoftArchive/redis/releases) and currently running it on the app server that hosts our MassTransit services - probably not best practice...

**Comment by thepirat000** [comment]
Please try with version 7.4.1. the sync `SetHashed` call was fixed. (give a few mins to the package to be indexed on nuget.org)

By the way, did you already tried increasing syncTimeout?

**Comment by moconnell** [comment]
Didn’t change any settings from default. 

Error-free in testing so far with 7.4.1 - looks good.

👍🏿🙏
