### ISSUE TITLE
Exception while trying to read spatial data from Redis through .Net Core application

### ISSUE THREAD

**Issue by shobaeswar** [thepirat000/CachingFramework.Redis#26]
I am using Caching Framework to read Spatial data from Redis using a .Net Core application. However, I face the below exception when I read the spatial data.

```
Exception message: Message = "Unexpected character encountered while parsing value: \u001f. Path '', line 0, position 0."
Stack trace:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CachingFramework.Redis.Serializers.JsonSerializer.Deserialize[T](Byte[] value)
   at CachingFramework.Redis.Providers.RedisGeoProvider.<GeoRadius>d__9`1.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
```
Below is the piece of code that reads the data.
```c#
var results = (ctx.GeoSpatial.GeoRadius<GeoData>(geoKey, center, radius, Unit.Miles)).ToList();
```
I published the data to redis through a standard .Net framework application. I am able to read the data through a standard .Net application (No issue with the JSON). However, I face issue while trying to read data from Redis using a .Net core application.  

P.S: I use .Net standard application to  push data to Redis because .Net Core doesn't support SQL Geography datatype yet.

**Comment by shobaeswar** [comment]
Thank you thepirat000. It works.
