### ISSUE TITLE
No connection is available to service this operation: GET

### ISSUE THREAD

**Issue by prachibansal01** [thepirat000/CachingFramework.Redis#60]
Suddenly we started getting "No Connection available" exception while accessing redis. Following is the exception -
"No connection is available to service this operation: GET xxxxx; SocketClosed on xxxxx/Interactive, origin: ProcessReadBytes, input-buffer: 0, outstanding: 0, last-read: 69s ago, last-write: 69s ago, unanswered-write: 2630s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago: RedisConnectionException
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2027 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1647
at CachingFramework.Redis.Providers.RedisCacheProvider.GetObject[T](String key)
at NetCoreUtilities.CachedUserObjectRedis.Get() in /codebuild/output/src803013914/src/NetCoreUtilities/CachedObjects/CachedUserObject.cs:line 63
at NetCoreUtilities.CachedUserObject.GetCachedUserObject(ElasticacheHelper elasticacheHelper, Int64 userID) in /codebuild/output/src803013914/src/NetCoreUtilities/CachedObjects/CachedUserObject.cs:line 82
at GetChildCategoriesAndAssets.Function.FunctionHandler(JObject input, ILambdaContext context) in /codebuild/output/src803013914/src/DIT Framework/users/GetChildCategoriesAndAssets.cs:line 54
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )"

We are using .Net framework 4.5 and CachingFramework.Redis 7.3.1.0, we tried using latest version of CachingFramework.Redis, but its seems it does not support .Net framework 4.5. It would be good if you help us in fixing this.

**Comment by thepirat000** [comment]
Can you share the code where it's failing? Do you create multiple `RedisContext` instances? You should have just one long-lived instance of `RedisContext`

Please check these issues: https://github.com/thepirat000/CachingFramework.Redis/issues/16 https://github.com/thepirat000/CachingFramework.Redis/issues/55

Also try with version 9.0.0 that is the latest compatible with 4.5

**Comment by prachibansal01** [comment]
I am  sharing part of my code

public class JsonElasticacheHelper
    {

        private static RedisContext _context = null;

        private double _expireTimeinHour = 1;
        string syncTimeOut = "60000";
        public string Environment { get; set; }

        public JsonElasticacheHelper(string cacheHostName, double expireTimeInHours, string environment, string connectionString)
        {
            try
            {
                if (_context == null)
                {
                    _context = new RedisContext(cacheHostName + ",SyncTimeout=" + syncTimeOut + ", " + "abortConnect = false", new CachingFramework.Redis.Serializers.JsonSerializer());
                    Logging.WriteToLog("Created new instance of context in ElasticCacheHelper (using json serializer)");
                    Logging.WriteToLog("Redis Connection established");
                }
                _expireTimeinHour = expireTimeInHours;
                Environment = environment;
            }
            catch (Exception ex)
            {
                Logging.WriteToLog(string.Format("Error in connection with Redis endpoint {0} : {1}", AWSSettings.Instance.CacheSettings.HostName, ex.ToString()), LoggingType.Redis);
            }

        }
		
		public T Get<T>(string redisKey)
        {
            return _context.Cache.GetObject<T>(redisKey); ;
        }
	}
	
	
	
	//Method to fetch object called UserDetails 
	
	public static UserDetails GetUserDetaills(string userID, AWSSettings awsSettings)
	{
		JsonElasticacheHelper elasticache = new JsonElasticacheHelper(awsSettings.HostName, double.Parse(awsSettings.ExpireTimeInHours), awsSettings.cacheEnvironment, awsSettings.DITSqlConnectionString);
		string redisKey = GetAssetDetailsRedisKey(userID)
		return  elasticache.Get<AssetDetails>(redisKey);
	}


We have used the code to perform redis operations(fetch/update/insert/delete) at many (100's) places in the code. We have also extensively used lua scripts. And this code we are using since last 1 year, but these errors started coming since last 2 weeks. And also they are happening very randomly - at random times and at random part of the code. We are not creating multiple instances of RedisContext. Its just that it gets initialized during every start of the application/service/lambda function.

Also now we have updated the latest framework of .net, updated the latest stable version of Caching Framework.redis. But still this is happening.

**Comment by thepirat000** [comment]
I'm pretty sure this problem is not related to this library nor the stackexchange.redis library. 
Have you seen [this](https://github.com/thepirat000/CachingFramework.Redis/issues/16#issuecomment-257621115) ?

Please check [this one](https://github.com/StackExchange/StackExchange.Redis/issues/12#issuecomment-54161230) also.

Redis is single-threaded and EVAL LUA scripts (as any other redis command) will block the database until completion. Since you extensively use LUA scripts, you are probably blocking connections or producing some kind of deadlock.

You should also avoud commands like [KEYS](https://redis.io/commands/keys) and consider increasing the amount of redis nodes.

**Comment by prachibansal01** [comment]
We have created a new cluster with 3 nodes, and tried adding a type of object of our application. We tried without lua scripts also. Added the data and fetched the data. But still we are facing same issue. And this new cluster is not being accessed by any other application at this time, so there can be no concurrent connections. Deadlock also I dont think there should be as connection is being created by a single application running locally on my system.

**Comment by prachibansal01** [comment]
Also there are few more observations which can help to reach the problem
1. When this exception comes the IsConnecting property of ConnectionMultiplexer is true. So it seems that Connection got disconnected and it is trying to connect but before that iteslf the command request went.
2. Also it seems that when this exception comes the RedisContext Object is not disposed, as it doesn't gets reinitialized.
I know I am asking you lot of questions, but I think there is some scenario about connections which we have missed in our code, so just trying to join the dots.

**Comment by thepirat000** [comment]
Can you share a project that reproduces the error locally?

**Comment by thepirat000** [comment]
Closing this for inactivity
